name: chit_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^11.1.6
  firebase_core: ^3.8.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  firebase_auth: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
